# file_setup\config.py
dataset_dir = "C:\\Users\\Sarah\\Documents\\AI-Creation\\Machine Learning\\Datasets\\Essays"
root_dir = "C:\\Users\\Sarah\\Documents\\AI-Creation\\Machine Learning\\Chatbot"
data_dir = "C:\\Users\\Sarah\\Documents\\AI-Creation\\Machine Learning\\Chatbot\\data"
database_dir = "C:\\Users\\Sarah\\Documents\\AI-Creation\\Machine Learning\\Chatbot\\data\\essays.db"
test_dir = "C:\\Users\\Sarah\\Documents\\AI-Creation\\Machine Learning\\Chatbot\\tests"
test_db_path = "C:\\Users\\Sarah\\Documents\\AI-Creation\\Machine Learning\\Chatbot\\tests\\test.db"
src_dir = "C:\\Users\\Sarah\\Documents\\AI-Creation\\Machine Learning\\Chatbot\\src"
web_dir = "C:\\Users\\Sarah\\Documents\\AI-Creation\\Machine Learning\\Chatbot\\src\\web"
model_dir = "C:\\Users\\Sarah\\Documents\\AI-Creation\\Machine Learning\\Chatbot\\src\\model"